name: Локализация
description: Ошибки перевода/дополнения - пишите здесь.
title: "Header: "
labels: [enhancement, bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: Проблема с переводом
      description: Опишите в чем заключается проблема. Можно приложить скриншоты.
    validations:
      required: true
